#
# Makefile for the sensors drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_SENSORS_CORE)	+= sensors_core.o
obj-$(CONFIG_SENSORS_K2DH)	+= k2dh.o
obj-$(CONFIG_SENSORS_K2HH)	+= k2hh.o
obj-$(CONFIG_SENSORS_AK8963C)	+= ak8963.o
obj-$(CONFIG_SENSORS_GP2A_PROXIMITY)	+= gp2a_proximity.o
obj-$(CONFIG_SENSORS_BMA255)	+= bma255.o
obj-$(CONFIG_SENSORS_AK09911C)	+= ak09911c.o
obj-$(CONFIG_SENSORS_TMD26713)	+= tmd26713.o
obj-$(CONFIG_SENSORS_TMD27723)	+= tmd27723.o
obj-$(CONFIG_SENSORS_CM36686)	+= cm36686.o
obj-$(CONFIG_SENSORS_GP2A0X0)	+= gp2a0x0.o
obj-$(CONFIG_SENSORS_SX9500)	+= sx9500.o
obj-$(CONFIG_SENSORS_ADPD142)	+= adpd142.o
obj-$(CONFIG_SENSORS_ALPS)	+= alps/
