/*
 * Copyright (c) 2012 Samsung Electronics Co., Ltd.
 *		http://www.samsung.com
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
*/

#ifndef __MACH_GPIO_SHANNON222AP_H
#define __MACH_GPIO_SHANNON222AP_H __FILE__

#define GPIO_FM_INT		EXYNOS4_GPX0(0)
#define GPIO_HOME_KEY		EXYNOS4_GPX0(1)
#define GPIO_2MIC_WAKE_UP	EXYNOS4_GPX0(2)
#ifdef CONFIG_SENSORS_HALL
#define GPIO_HALL_SENSOR_INT	EXYNOS4_GPX0(2)
#endif
#if defined(CONFIG_W1)
#define GPIO_COVER_ID       EXYNOS4_GPM0(3)
#endif

/* Camera */
#define GPIO_TORCH_EN		EXYNOS4_GPM3(4)
#define GPIO_FLASH_EN		EXYNOS4_GPM3(6)
#define GPIO_CAM_SEN_CORE	EXYNOS4_GPM1(6)
#define GPIO_CAM_MCLK		EXYNOS4_GPM2(2)

#define GPIO_SENSOR_EN		EXYNOS4_GPX0(3)
#define GPIO_SDHI0_CD		EXYNOS4_GPX0(4)
#define GPIO_TOUCH_KEY_INT	EXYNOS4_GPX0(5)
#define GPIO_PMIC_IRQN		EXYNOS4_GPX0(6)
#define GPIO_PMIC_ONOB		EXYNOS4_GPX0(7)

#define GPIO_OPTION_KEY		EXYNOS4_GPX1(0)
#define GPIO_MAIN_CAM_RST	EXYNOS4_GPX1(2)
#define GPIO_CHG_INT		EXYNOS4_GPX1(3)
#define GPIO_VOL_UP		EXYNOS4_GPX1(4)
#define GPIO_VOL_DOWN		EXYNOS4_GPX1(5)
#define GPIO_CODEC_INT		EXYNOS4_GPX1(6)
#define GPIO_NFS_IRQ		EXYNOS4_GPX1(7)

#define GPIO_WLAN_SDIO_DAT1	EXYNOS4_GPX2(0)
#define GPIO_MHL_WAKE_UP	EXYNOS4_GPX2(1)
#define GPIO_MHL_INT		EXYNOS4_GPX2(2)
#define GPIO_MHL_RST		EXYNOS4_GPX2(3)
#define GPIO_DSI0_RST_N		EXYNOS4_GPX2(4)
#define GPIO_GPS_PWR_EN		EXYNOS4_GPX2(5)
#define GPIO_KEY_LED_EN		EXYNOS4_GPX2(6)
#define GPIO_PROXI_INT		EXYNOS4_GPX2(7)

#define GPIO_GYRO_INT		EXYNOS4_GPX3(0)
#define GPIO_LCD_EDS_DETTECT	EXYNOS4_GPX3(1)
#define GPIO_CHG_DET		EXYNOS4_GPX3(2)
#define GPIO_MUS_INT_N		EXYNOS4_GPX3(3)

#define GPIO_TSP_INT		EXYNOS4_GPX3(5)
#define GPIO_TSP_SDA		EXYNOS4_GPA1(2)
#define GPIO_TSP_SCL		EXYNOS4_GPA1(3)
#define TSP_VENDOR_1		EXYNOS4_GPM0(2)
#define TSP_VENDOR_2		EXYNOS4_GPM0(4)

#define GPIO_MHL_SDA_18V	EXYNOS4_GPA1(4)
#define GPIO_MHL_SCL_18V	EXYNOS4_GPA1(5)

#define GPIO_TOUCHKEY_SDA	EXYNOS4_GPB(0)
#define GPIO_TOUCHKEY_SCL	EXYNOS4_GPB(1)

/* muic gpio */
#define GPIO_UART_SEL		EXYNOS4_GPC1(0)
#define GPIO_MUIC_SDA		EXYNOS4_GPC1(2)
#define GPIO_MUIC_SCL		EXYNOS4_GPC1(1)
#define GPIO_MUIC_IRQ		EXYNOS4_GPX3(3)

#define GPIO_GPS_UART_RXD	EXYNOS4_GPA0(4)
#define GPIO_GPS_UART_TXD	EXYNOS4_GPA0(5)
#define GPIO_GPS_UART_CTS	EXYNOS4_GPA0(6)
#define GPIO_GPS_UART_RTS	EXYNOS4_GPA0(7)

#if defined(CONFIG_MACH_KMINI)
#define GPIO_MOTOR_EN		EXYNOS4_GPM3(2)
#elif defined(CONFIG_MACH_DEGAS)
#define GPIO_MOTOR_EN		EXYNOS4_GPM3(2)
#elif defined(CONFIG_MACH_GARDA)
#define GPIO_DOC_SWITCH		EXYNOS4_GPX1(1)
#endif

#endif
/* __MACH_GPIO_SHANNON222Ap_H */
