#ifndef __GPIO_REV_NEO__
#define __GPIO_REV_NEO__

#define AP_PD_GPIO_COUNT_REV_NEO 121
#define AP_INIT_GPIO_COUNT_REV_NEO 19
#define INTERRUPT_SLEEP_GPIO_COUNT_REV_NEO 14
#define INTERRUPT_INIT_GPIO_COUNT_REV_NEO 9

 unsigned int init_gpio_table_rev_neo[AP_INIT_GPIO_COUNT_REV_NEO][3] =
{
	{ EXYNOS3_GPC1(1), S3C_GPIO_INPUT, S3C_GPIO_PULL_DOWN },			/* NC */

	{ EXYNOS3_GPD0(2), S3C_GPIO_INPUT, S3C_GPIO_PULL_NONE},			/* MUIC_SDA */
	{ EXYNOS3_GPD0(3), S3C_GPIO_INPUT, S3C_GPIO_PULL_NONE },			/* MUIC_SCL*/

	{ EXYNOS3_GPD1(0), S3C_GPIO_SFN(0x2), S3C_GPIO_PULL_NONE },			/* AP_PMIC_SDA */
	{ EXYNOS3_GPD1(1), S3C_GPIO_SFN(0x2), S3C_GPIO_PULL_NONE },			/* AP_PMIC_SCL */
	{ EXYNOS3_GPD1(2), S3C_GPIO_INPUT, S3C_GPIO_PULL_NONE },			/* FUEL_SDA */
	{ EXYNOS3_GPD1(3), S3C_GPIO_INPUT, S3C_GPIO_PULL_NONE },			/* FUEL_SCL */

	{ EXYNOS3_GPE0(2), S3C_GPIO_INPUT, S3C_GPIO_PULL_DOWN },			/* NC */
	{ EXYNOS3_GPE0(6), S3C_GPIO_OUTPUT, S3C_GPIO_PULL_NONE },			/* FPGA_SPI_EN */
	#if 0 /* it's occured to kernel panic */
	{ EXYNOS3_GPK0(0), S3C_GPIO_INPUT, S3C_GPIO_PULL_DOWN },			/* TP*/
	#endif

	{ EXYNOS3_GPK1(0), S3C_GPIO_INPUT, S3C_GPIO_PULL_DOWN },   		/* WLAN_SD_CLK */
	{ EXYNOS3_GPK1(1), S3C_GPIO_INPUT, S3C_GPIO_PULL_NONE },     		/* WLAN_SD_CMD */
	{ EXYNOS3_GPK1(2), S3C_GPIO_INPUT, S3C_GPIO_PULL_DOWN },			/* NC */

	{ EXYNOS3_GPK2(0), S3C_GPIO_INPUT, S3C_GPIO_PULL_DOWN },			/* NC */
	{ EXYNOS3_GPK2(1), S3C_GPIO_INPUT, S3C_GPIO_PULL_DOWN },			/* NC */
	{ EXYNOS3_GPK2(2), S3C_GPIO_INPUT, S3C_GPIO_PULL_DOWN },			/* NC */
	{ EXYNOS3_GPK2(3), S3C_GPIO_INPUT, S3C_GPIO_PULL_DOWN },			/* NC */
	{ EXYNOS3_GPK2(4), S3C_GPIO_INPUT, S3C_GPIO_PULL_DOWN },			/* NC */
	{ EXYNOS3_GPK2(5), S3C_GPIO_INPUT, S3C_GPIO_PULL_DOWN },			/* NC */
	{ EXYNOS3_GPK2(6), S3C_GPIO_INPUT, S3C_GPIO_PULL_DOWN },			/* NC */
};

unsigned int init_gpio_table_alive_rev_neo[INTERRUPT_INIT_GPIO_COUNT_REV_NEO][3]=
{
	{EXYNOS3_GPX1(4), S3C_GPIO_INPUT, S3C_GPIO_PULL_NONE},	/*CODEC_IRQ*/
	{EXYNOS3_GPX1(5), S3C_GPIO_SFN(0xf), S3C_GPIO_PULL_NONE},	/*CHG_INTB*/

	{EXYNOS3_GPX2(0), S3C_GPIO_INPUT, S3C_GPIO_PULL_DOWN},	/*NC*/
	{EXYNOS3_GPX2(1), S3C_GPIO_INPUT, S3C_GPIO_PULL_DOWN},	/*NC*/
	{EXYNOS3_GPX2(2), S3C_GPIO_INPUT, S3C_GPIO_PULL_DOWN},	/*CAM_STBY*/
	{EXYNOS3_GPX2(3), S3C_GPIO_INPUT, S3C_GPIO_PULL_DOWN},	/*NC*/

	{EXYNOS3_GPX3(2), S3C_GPIO_INPUT, S3C_GPIO_PULL_DOWN},	/*NC*/
	#if 0
	{EXYNOS3_GPX3(3), S3C_GPIO_INPUT, S3C_GPIO_PULL_DOWN},	/*NC*/
	#endif
	{EXYNOS3_GPX3(4), S3C_GPIO_INPUT, S3C_GPIO_PULL_DOWN},	/*NC*/
	{EXYNOS3_GPX3(7), S3C_GPIO_INPUT, S3C_GPIO_PULL_DOWN},	/*NC*/
};

unsigned int sleep_gpio_table_alive_rev_neo[INTERRUPT_SLEEP_GPIO_COUNT_REV_NEO][3] =
{
	{EXYNOS3_GPX0(1), S3C_GPIO_INPUT, S3C_GPIO_PULL_DOWN},	/*NC*/

	{EXYNOS3_GPX1(3), S3C_GPIO_INPUT, S3C_GPIO_PULL_DOWN},	/*NC*/
	{EXYNOS3_GPX1(4), S3C_GPIO_INPUT, S3C_GPIO_PULL_NONE},	/*CODEC_IRQ*/
	{EXYNOS3_GPX1(5), S3C_GPIO_SFN(0xf), S3C_GPIO_PULL_NONE},	/*CHG_INTB*/
	{EXYNOS3_GPX1(6), S3C_GPIO_INPUT, S3C_GPIO_PULL_DOWN},	/*NC*/

	{EXYNOS3_GPX2(0), S3C_GPIO_INPUT, S3C_GPIO_PULL_DOWN},	/*NC*/
        {EXYNOS3_GPX2(1), S3C_GPIO_INPUT, S3C_GPIO_PULL_DOWN},	/*NC*/
        {EXYNOS3_GPX2(2), S3C_GPIO_INPUT, S3C_GPIO_PULL_DOWN},	/*CAM_STBY*/
        {EXYNOS3_GPX2(3), S3C_GPIO_INPUT, S3C_GPIO_PULL_DOWN},	/*NC*/

	{EXYNOS3_GPX3(0), S3C_GPIO_INPUT, S3C_GPIO_PULL_DOWN},	/*NC*/
	{EXYNOS3_GPX3(2), S3C_GPIO_INPUT, S3C_GPIO_PULL_DOWN},	/*NC*/
	{EXYNOS3_GPX3(3), S3C_GPIO_INPUT, S3C_GPIO_PULL_DOWN},	/*NC*/
	{EXYNOS3_GPX3(4), S3C_GPIO_INPUT, S3C_GPIO_PULL_DOWN},	/*NC*/
	{EXYNOS3_GPX3(7), S3C_GPIO_INPUT, S3C_GPIO_PULL_DOWN},	/*NC*/
};

unsigned int sleep_gpio_table_pd_neo_rev_neo[AP_PD_GPIO_COUNT_REV_NEO][3] =
{
	{EXYNOS3_GPA0(0),  S5P_GPIO_PD_INPUT, S5P_GPIO_PD_UPDOWN_DISABLE},	 /* BT_UART_RXD */
	{EXYNOS3_GPA0(1),  S5P_GPIO_PD_OUTPUT1, S5P_GPIO_PD_UPDOWN_DISABLE},	 /* BT_UART_TXD */
	{EXYNOS3_GPA0(2),  S5P_GPIO_PD_INPUT, S5P_GPIO_PD_UPDOWN_DISABLE},	 /* BT_UART_CTS */
	{EXYNOS3_GPA0(3),  S5P_GPIO_PD_OUTPUT1, S5P_GPIO_PD_UPDOWN_DISABLE},	 /* BT_UART_RTS */
	{EXYNOS3_GPA0(4),  S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE},	 /* AP_RXD */
	{EXYNOS3_GPA0(5),  S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE},	 /* AP_TXD */
	{EXYNOS3_GPA0(6),  S5P_GPIO_PD_INPUT, S5P_GPIO_PD_UPDOWN_DISABLE},	 /* TSP_SDA */
	{EXYNOS3_GPA0(7),  S5P_GPIO_PD_INPUT, S5P_GPIO_PD_UPDOWN_DISABLE},	 /* TSP_SCL */

	{ EXYNOS3_GPA1(0), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE },		/* NC */
	{ EXYNOS3_GPA1(1), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE },		/* NC */
	{ EXYNOS3_GPA1(2), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_UPDOWN_DISABLE },	/* FPGA_SPI_SI*/
	{ EXYNOS3_GPA1(3), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_UPDOWN_DISABLE },	/* FPGA_SPI_CLK  */
	{ EXYNOS3_GPA1(4), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE },	/* NC */
	{ EXYNOS3_GPA1(5), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE },	/* NC */

	{ EXYNOS3_GPB(0),  S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE },		/* SHUB_SPI_SCK */
	{ EXYNOS3_GPB(1),  S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE },		/* SHUB_SPI_SSN */
	{ EXYNOS3_GPB(2),  S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE },		/* SHUB_SPI_MISO */
	{ EXYNOS3_GPB(3),  S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE },		/* SHUB_SPI_MOSI */
	{ EXYNOS3_GPB(4), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE },	/* CODEC_SPI_SCK */
	{ EXYNOS3_GPB(5), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE },		/* CODEC_SPI_SS_N */
	{ EXYNOS3_GPB(6), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE },		/* CODEC_SPI_MISO */
	{ EXYNOS3_GPB(7), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE },	/* CODEC_SPI_MOSI */

	{ EXYNOS3_GPC0(0), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE },	 			 /* NC */
	{ EXYNOS3_GPC0(1), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE },				 /* NC */
	{ EXYNOS3_GPC0(2), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE },				 /* NC */
	{ EXYNOS3_GPC0(3), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE },				 /* NC */
	{ EXYNOS3_GPC0(4), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE },				 /* NC */

	{ EXYNOS3_GPC1(0), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE },				/* MM_I2S_CLK */
	{ EXYNOS3_GPC1(1), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE },				/* NC */
	{ EXYNOS3_GPC1(2), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE },				/* MM_I2S_SYNC */
	{ EXYNOS3_GPC1(3), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE },				/* MM_I2S_DI */
	{ EXYNOS3_GPC1(4), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE },				/* MM_I2S_DO */

	{ EXYNOS3_GPD0(0), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE },				/* NC */
	{ EXYNOS3_GPD0(1), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE },				/* NC */
	{ EXYNOS3_GPD0(2), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_UPDOWN_DISABLE },				/* MUIC_SDA */
	{ EXYNOS3_GPD0(3), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_UPDOWN_DISABLE },     		/* MUIC_SCL */

	{ EXYNOS3_GPD1(0), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_UPDOWN_DISABLE },     		/* AP_PMIC_SDA */
	{ EXYNOS3_GPD1(1), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_UPDOWN_DISABLE },     		/* AP_PMIC_SCL */
	{ EXYNOS3_GPD1(2), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_UPDOWN_DISABLE },     		/* FUEL_SCL */
	{ EXYNOS3_GPD1(3), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_UPDOWN_DISABLE },    			/* FUEL_SDA */

	{ EXYNOS3_GPE0(0), S5P_GPIO_PD_PREV_STATE, S5P_GPIO_PD_UPDOWN_DISABLE },        /* BT_EN */
	{ EXYNOS3_GPE0(1), S5P_GPIO_PD_PREV_STATE, S5P_GPIO_PD_DOWN_ENABLE },        			/* DISP_RST */
	{ EXYNOS3_GPE0(2), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE },       			/* NC */
	{ EXYNOS3_GPE0(3), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE },       			/* NC */
	{ EXYNOS3_GPE0(4), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE },      		/* WLAN_EN */
	{ EXYNOS3_GPE0(5), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE },        			/* NC */
	{ EXYNOS3_GPE0(6), S5P_GPIO_PD_OUTPUT0, S5P_GPIO_PD_UPDOWN_DISABLE },        			/* FPGA_SPI_EN */
	{ EXYNOS3_GPE0(7), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE },        			/* NC */


	{ EXYNOS3_GPE1(0), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE },        			/* NC */
	{ EXYNOS3_GPE1(1), S5P_GPIO_PD_PREV_STATE, S5P_GPIO_PD_UPDOWN_DISABLE },        	/* WRSTBI */
	{ EXYNOS3_GPE1(2), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE },       			/* NC */
	{ EXYNOS3_GPE1(3), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE },     			/* NC */
	{ EXYNOS3_GPE1(4), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE },     			/* NC */
	{ EXYNOS3_GPE1(5), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE },        			/* NC */
	{ EXYNOS3_GPE1(6), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE },       			/* NC */
	{ EXYNOS3_GPE1(7), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_UPDOWN_DISABLE },     		/* HW_REV0 */

	{ EXYNOS3_GPE2(0), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_UPDOWN_DISABLE },     		/* HW_REV1 */
	{ EXYNOS3_GPE2(1), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_UPDOWN_DISABLE },    			 /* HW_REV2 */
	{ EXYNOS3_GPE2(2), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_UPDOWN_DISABLE },     		/* HW_REV3 */

	{ EXYNOS3_GPK0(0), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE },       			/* TP */
	{ EXYNOS3_GPK0(1), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_UPDOWN_DISABLE },  			/* NAND_CMD */
	{ EXYNOS3_GPK0(2), S5P_GPIO_PD_OUTPUT0, S5P_GPIO_PD_UPDOWN_DISABLE },        	/* eMMC_EN */
	{ EXYNOS3_GPK0(3), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_UPDOWN_DISABLE }, 				/* NAND_D0 */
	{ EXYNOS3_GPK0(4), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_UPDOWN_DISABLE },  			/* NAND_D1 */
	{ EXYNOS3_GPK0(5), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_UPDOWN_DISABLE }, 				/* NAND_D2 */
	{ EXYNOS3_GPK0(6), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_UPDOWN_DISABLE }, 				/* NAND_D3 */
	{ EXYNOS3_GPK0(7), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE }, 				/* 10K PD */

	{ EXYNOS3_GPK1(0), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE },   			/* WLAN_SD_CLK */
	{ EXYNOS3_GPK1(1), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_UPDOWN_DISABLE },     		/* WLAN_SD_CMD */
	{ EXYNOS3_GPK1(2), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE },        			/* NC */
	{ EXYNOS3_GPK1(3), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_UPDOWN_DISABLE },     		/* WLAN_SD_D0 */
	{ EXYNOS3_GPK1(4), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_UPDOWN_DISABLE },     		/* WLAN_SD_D1 */
	{ EXYNOS3_GPK1(5), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_UPDOWN_DISABLE },     		/* WLAN_SD_D2 */
	{ EXYNOS3_GPK1(6), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_UPDOWN_DISABLE },     		/* WLAN_SD_D3 */

	{ EXYNOS3_GPK2(0), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE },       			/* NC */
	{ EXYNOS3_GPK2(1), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE },        			/* NC */
	{ EXYNOS3_GPK2(2), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE },       			/* NC */
	{ EXYNOS3_GPK2(3), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE },       			/* NC */
	{ EXYNOS3_GPK2(4), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE },        			/* NC */
	{ EXYNOS3_GPK2(5), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE },        			/* NC */
	{ EXYNOS3_GPK2(6), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE },        			/* NC */

	{ EXYNOS3_GPL0(0), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_UPDOWN_DISABLE },  			/* NAND_D4 */
	{ EXYNOS3_GPL0(1), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_UPDOWN_DISABLE },  			/* NAND_D5 */
	{ EXYNOS3_GPL0(2), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_UPDOWN_DISABLE },  			/* NAND_D6 */
	{ EXYNOS3_GPL0(3), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_UPDOWN_DISABLE },  			/* NAND_D7 */

	{ EXYNOS3_GPM0(0), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE },       			/* NC */
	{ EXYNOS3_GPM0(1), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE },        			/* NC */
	{ EXYNOS3_GPM0(2), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE },       			/* NC */
	{ EXYNOS3_GPM0(3), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE },       			/* NC */
	{ EXYNOS3_GPM0(4), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE },        			/* NC */
	{ EXYNOS3_GPM0(5), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE },       			/* NC */
	{ EXYNOS3_GPM0(6), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE },        			/* NC */
	{ EXYNOS3_GPM0(7), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE },        			/* NC */

	{ EXYNOS3_GPM1(0), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE },        			/* NC */
	{ EXYNOS3_GPM1(1), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE },        			/* NC */
	{ EXYNOS3_GPM1(2), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE },        			/* NC */
	{ EXYNOS3_GPM1(3), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE },        			/* NC */
	{ EXYNOS3_GPM1(4), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE },        			/* NC */
	{ EXYNOS3_GPM1(5), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE },        			/* NC */
	{ EXYNOS3_GPM1(6), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE },        			/* NC */

	{ EXYNOS3_GPM2(0), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE },        			/* NC */
	{ EXYNOS3_GPM2(1), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE },        			/* NC */
	{ EXYNOS3_GPM2(2), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE },        			/* NC */
	{ EXYNOS3_GPM2(3), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE },       			/* NC */
	{ EXYNOS3_GPM2(4), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE },        			/* NC */

	{ EXYNOS3_GPM3(0), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE },      			/* NC */
	{ EXYNOS3_GPM3(1), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE },        			/* NC */
	{ EXYNOS3_GPM3(2), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE },        			/* NC */
	{ EXYNOS3_GPM3(3), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE },        			/* NC */
	{ EXYNOS3_GPM3(4), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE },        			/* NC */
	{ EXYNOS3_GPM3(5), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE },        			/* NC */
	{ EXYNOS3_GPM3(6), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE },        			/* NC */
	{ EXYNOS3_GPM3(7), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE },        			/* NC */

	{ EXYNOS3_GPM4(0), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE },     			/* NC */
	{ EXYNOS3_GPM4(1), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE },    			/* NC */
	{ EXYNOS3_GPM4(2), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE },       			/* NC  */
	{ EXYNOS3_GPM4(3), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE },       			/* NC */
	{ EXYNOS3_GPM4(4), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE },      			/* NC */
	{ EXYNOS3_GPM4(5), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE },        			/* NC */
	{ EXYNOS3_GPM4(6), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE },       			/* NC */
	{ EXYNOS3_GPM4(7), S5P_GPIO_PD_INPUT, S5P_GPIO_PD_DOWN_ENABLE },       			/* NC */
};


#endif
